#!/usr/bin/env python3
"""
Convert an audio file into embedded_song.h for OscilloSketch Embedded Song mode.
Recommended first command:
  py make_embedded_song.py "song.mp3" --seconds 30 --rate 16000 --channels 2
Requires pydub and ffmpeg.
"""
from __future__ import annotations
import argparse
from pathlib import Path
from typing import Iterable
try:
    from pydub import AudioSegment
except ImportError as exc:
    raise SystemExit("Missing pydub. Install with: py -m pip install pydub\nAlso install ffmpeg and put it on PATH.") from exc

def iter_int16_le(raw: bytes) -> Iterable[int]:
    if len(raw) % 2:
        raw = raw[:-1]
    for i in range(0, len(raw), 2):
        v = raw[i] | (raw[i + 1] << 8)
        if v >= 32768:
            v -= 65536
        yield v

def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("input", help="Input MP3/WAV/etc.")
    ap.add_argument("--out", default="embedded_song.h", help="Output header path")
    ap.add_argument("--seconds", type=float, default=30.0, help="Seconds to embed")
    ap.add_argument("--start", type=float, default=0.0, help="Start time in seconds")
    ap.add_argument("--rate", type=int, default=16000, help="PCM sample rate")
    ap.add_argument("--channels", type=int, choices=(1, 2), default=2, help="2=stereo XY, 1=smaller mono")
    ap.add_argument("--gain", type=float, default=0.80, help="Linear PCM gain before embedding")
    args = ap.parse_args()
    if args.seconds <= 0 or args.rate <= 0 or args.gain <= 0:
        raise SystemExit("--seconds, --rate, and --gain must be positive")
    in_path = Path(args.input)
    out_path = Path(args.out)
    print(f"Loading: {in_path}")
    seg = AudioSegment.from_file(in_path)
    start_ms = int(round(args.start * 1000.0))
    end_ms = start_ms + int(round(args.seconds * 1000.0))
    seg = seg[start_ms:end_ms]
    seg = seg.set_frame_rate(args.rate).set_channels(args.channels).set_sample_width(2)
    samples = []
    peak_in = 0
    peak_out = 0
    for v in iter_int16_le(seg.raw_data):
        peak_in = max(peak_in, abs(v))
        scaled = int(round(v * args.gain))
        if scaled > 32767:
            scaled = 32767
        elif scaled < -32768:
            scaled = -32768
        peak_out = max(peak_out, abs(scaled))
        samples.append(scaled)
    frames = len(samples) // args.channels
    bytes_pcm = len(samples) * 2
    print(f"Converted to {args.rate} Hz, {args.channels} channel(s), signed 16-bit PCM")
    print(f"Frames: {frames}")
    print(f"Duration: {frames / args.rate:.2f} s")
    print(f"PCM bytes in firmware: {bytes_pcm:,} bytes ({bytes_pcm / (1024 * 1024):.2f} MiB)")
    print(f"Input peak: {peak_in}, embedded peak after gain: {peak_out}")
    with out_path.open("w", newline="\n") as f:
        f.write("#pragma once\n")
        f.write("#include <Arduino.h>\n\n")
        f.write("// Auto-generated by make_embedded_song.py. Do not edit by hand.\n")
        f.write(f"// Source: {in_path.name}\n")
        f.write(f"// Duration: {frames / args.rate:.2f} s\n")
        f.write(f"constexpr uint32_t EMBEDDED_SONG_SAMPLE_RATE = {args.rate};\n")
        f.write(f"constexpr uint8_t EMBEDDED_SONG_CHANNELS = {args.channels};\n")
        f.write(f"constexpr size_t EMBEDDED_SONG_FRAMES = {frames};\n\n")
        f.write("const int16_t EMBEDDED_SONG_PCM[] PROGMEM = {\n")
        per_line = 12
        for i in range(0, len(samples), per_line):
            chunk = samples[i:i + per_line]
            f.write("  " + ", ".join(str(x) for x in chunk))
            if i + per_line < len(samples):
                f.write(",")
            f.write("\n")
        f.write("};\n")
    print(f"Wrote: {out_path}")

if __name__ == "__main__":
    main()
